export default function PrivacyPolicy() {
    const h1Style = "scroll-m-20 text-2xl font-bold tracking-tight lg:text-2xl py-2";
    const h2Style = "scroll-m-20 text-xl tracking-tight lg:text-xl py-2";
    const textStyle = "py-2 text-xs";
  return (
    <div>
        <h1 className={h1Style}>Privacy Policy</h1>
        <p className={textStyle}>Last Update: 10/05/2023 (Subscription/Pay Wall Version not implemented in Version 1.0)</p>
        <h2 className={h2Style}>Introduction</h2>
        <p className={textStyle}>Our privacy policy (the “Privacy Policy”) explains the information we collect, how we use and share it, how to manage your privacy controls and your rights in connection with our websites and the related mobile applications and services (collectively, the “Services”). Please also read our Terms of Service which sets out the terms governing the Services.</p>
        <p className={textStyle}>Argos LLC is headquartered in Dallas,Texas, USA and our Services are provided to you by Argos LLC,</p>
        <p className={textStyle}>This policy was written in English. To the extent a translated version conflicts with the English version, the English version controls. Unless indicated otherwise, this Privacy Policy does not apply to our subsidiaries (which have their own privacy policies) or third party products or services, including other companies you might interact with on or through the Services.</p>
        <p className={textStyle}>Questions or comments about this Privacy Policy may be submitted by mail or email using the contact information below</p>
        <p className={textStyle}>Argos LLC</p>
        <p className={textStyle}>Attn: Legal</p>
        <p className={textStyle}>Argos@Argosapp.net</p>

        <h1 className={h1Style}>Information Argos LLC Collects</h1>
        <p className={textStyle}>Argos LLC collects information about you, including information that directly or indirectly identifies you, if you or your other Argos LLC users choose to share it with Argos LLC . We receive information in a few different ways, including when you track, complete or upload activities using the Services. Argos LLC also collects information about how you use the Services. There are also several opportunities for you to share information about yourself, your friends, and your activities with Argos LLC . For example:</p>

        <h2 className={h2Style}>Account, Profile, Activity, and Use Information</h2>
        <p className={textStyle}>We collect basic account information such as your name, email address, date of birth, gender, weight, username and password that helps secure and provide you with access to our Services. We also use dates of birth to enhance safety and privacy for our younger users, to place you on age-group leaderboards, and to provide more accurate performance analysis.</p>
        <p className={textStyle}>Profile, activity and use information is collected about you when you choose to upload a picture, video, post, or activity (including date, time and geo-location information as well as your speed and pace and perceived exertion), join a challenge, add your equipment usage, view others' activities, or otherwise use the Services.</p>
        <p className={textStyle}>We use your contact information so we can contact you when needed. For example, to respond to your support requests.</p>

        <h2 className={h2Style}>Location Information</h2>
        <p className={textStyle}>We collect and process location information when you sign up for and use the Services. We do not track your device location while you are not using the Services. But in order to use our core features (e.g., GPS activity tracking, routes, segment leaderboards, etc.), it is necessary for you to permit us to track your device location while you use the Services. If you would like to stop the device location tracking, you may do so at any time by adjusting your device settings.</p>

        <h2 className={h2Style}>Content You Share</h2>
        <p className={textStyle}>We gather information from the photos, videos, posts, comments, kudos, ratings, reviews, and other content you share on the Services, including when you participate in partner events or create segments or routes.</p>

        <h2 className={h2Style}>Contacts Information</h2>
        <p className={textStyle}>You can choose to add your contacts' information by connecting your contacts from your mobile device or social networking accounts to Argos LLC . If you choose to share your contacts with Argos LLC , we will, in accordance with your instructions, access and store your contacts' information in order to identify potential connections and help you connect with them. Learn more about how we collect information about your contacts, how we use that information, and the controls available to you.</p>

        <h2 className={h2Style}>Connected Devices and Apps</h2>
        <p className={textStyle}>Argos LLC collects information from devices and apps you connect to Argos LLC. For example, you may connect your Garmin watch or Flywheel account to Argos LLC and information from these devices and apps will be passed along to Argos LLC .</p>

        <h2 className={h2Style}>Health Information</h2>
        <p className={textStyle}>Argos LLC may collect or infer health information. Certain health information may be inferred from sources such as heart rate or other measurements, including power, cadence, and weight or other indicators. Before you can upload health information to Argos LLC , you must give your explicit consent to the processing of that health information by Argos LLC . You can withdraw your consent to Argos LLC processing your health information at any time. You can also hide certain statistics, such as your heart rate, from being viewed by others on individual activities.</p>

        <h2 className={h2Style}>Payment Information</h2>
        <p className={textStyle}>When you make a payment on Argos LLC , you may provide payment information such as your payment card or other payment details. We use Payment Card Industry (PCI) compliant third-party payment services and we do not store your credit card information.</p>

        <h2 className={h2Style}>Third-Party Accounts</h2>
        <p className={textStyle}>Argos LLC allows you to sign up and log in to the Services using accounts you create with third-party products and services, such as Meta, Google, or Apple (collectively, “Third-Party Accounts”). If you access the Services with Third-Party Accounts we will collect information that you have agreed to make available such as your name, email address, profile information and preferences. This information is collected by the Third-Party Account providers and is provided to Argos LLC under their privacy policies. You can generally control the information that we receive from these sources using the privacy controls in your Third-Party Account.</p>

        <h2 className={h2Style}>Technical Information and Log Files</h2>
        <p className={textStyle}>We collect information from your browser, computer, or mobile device, which provides us with technical information when you access or use the Services. This technical information includes device and network information, cookies, log files and analytics information. Learn more about how we use cookies and manage your preferences by visiting our Cookie Policy.</p>
        <p className={textStyle}>The Services use log files. The information stored in those files includes IP addresses, browser type, internet service provider (ISP), referring/exit pages, platform type, date/time stamp, and number of clicks. This information is used to analyze trends, administer, protect and secure the Services, track user movement in the aggregate, and gather broad demographic information (e.g., country residence) for aggregate use. IP addresses may be linked to session IDs, athlete IDs and device identifiers.</p>
        
        <h2 className={h2Style}>Other Information</h2>
        <p className={textStyle}>We may collect information directly from you or through our service providers, such as when we collect your feedback through surveys.</p>
        <p className={textStyle}>We may also collect information about you from other Argos LLC users such as when they give you kudos or comment on your activities.</p>

        <h1 className={h1Style}>How Argos LLC Uses Information</h1>
        <p className={textStyle}>Argos LLC uses the information we collect and receive as described below.</p>
        <h2 className={h2Style}>To provide the Services</h2>
        <p className={textStyle}>We use the information we collect and receive to provide the Services, including providing you with the ability to:</p>
        <ul className={textStyle}>
            <li>&#8226; Record your activities and analyze your performance. For example, to compare your past efforts, analyze your training, and - with your consent - use your heart rate information to provide you with interesting and useful performance analysis. We may also match your GPS activities to specific segments or routes to analyze your efforts against those of other users and to establish leaderboards.</li>
            <li>&#8226; Interact with other users. For example, to compete in segments, participate in clubs, challenges, or events, follow other users.</li>
            <li>&#8226; Manage your training. For example, to set goals and use your training dashboard.</li>
            <li>&#8226; Share insights with the Argos LLC community. For example, by sharing your public reviews and photos of specific routes or segments. We may also analyze your public photos from specific routes or segments to attach characteristics to those routes or segments (e.g., shaded, waterfalls, flowers, etc.)</li>
        </ul>
        <p className={textStyle}>Subject to your privacy controls, your information, including parts of your profile, username, photos/videos, users you follow and who follow you, clubs you belong to on Argos LLC , your activities, the devices you use, and kudos and comments you give and receive will be shared on Argos LLC so that you may be able to participate in the Services, for example to show your place on a leaderboard. Certain information (e.g., your name, and some profile information) is also available to non-users on the web. Your precise location information, such as where you run or ride, may also be shared on Argos LLC or to non-users, in accordance with your privacy controls.</p>

        <h2 className={h2Style}>To customize your experience</h2>
        <p className={textStyle}>We use the information we collect and receive to customize your experience. For example, we may suggest segments, routes, challenges, or clubs on Argos LLC that may interest you, users that you may want to follow, or new features that you may want to try. For example, if we know that you like to hike, we may tell you about new hiking routes or show you sponsored content related to hiking. Or if we see that you bike ride in a certain area, we may suggest joining a club or a race in that area.</p>
        <h2 className={h2Style}>To provide you with targeted promotions</h2>
        <p className={textStyle}>We use the information we collect and receive to serve you with relevant promotions, subject to your notification and email preferences. For example, if we see you are an active user who has been on a monthly subscription plan for an extended period of time, we may serve you a promotion to switch to a discounted annual plan. Or if you are an active user who has never subscribed, we may send you an offer for a free subscription trial.</p>
        <h2 className={h2Style}>To protect you and the Services</h2>
        <p className={textStyle}>We use the information we collect and receive to protect users, enforce our Terms of Service, Acceptable Use Policy, and Community Standards, and promote safety. For example, we find and remove content that violates our terms, such as hate speech or spam, as well as suspend or terminate accounts that share such content. Argos LLC reserves the right to review accounts and user actions on the Services to ensure compliance with our Terms. You can learn more about how to report content that violates our terms and standards.</p>
        <h2 className={h2Style}>To assist you with a support request</h2>
        <p className={textStyle}>We use the information we collect and receive to provide support in response to your requests and comments. Depending on your request, this may require us to access your account, for example, to troubleshoot or replicate a reported issue.</p>
        <h2 className={h2Style}>To improve our Services</h2>
        <p className={textStyle}>We also use the information we collect and receive to conduct research, and to analyze, develop, troubleshoot, and improve the Services. To do this, Argos LLC may use third-party analytics providers to gain insights into how our Services are used, using aggregated data, and to help us improve the Services.</p>
        <h2 className={h2Style}>To communicate with you</h2>
        <p className={textStyle}>We may also use the information we collect and receive to market and promote the Services, activities and events on Argos LLC , and other commercial products or services, including using email and push notifications, in accordance with your preferences. We may also contact you for partnership opportunities, when investigating alleged violations of our terms, or to send proactive customer support messages.</p>
        <h2 className={h2Style}>To process your subscription</h2>
        <p className={textStyle}>We use the information we collect to process your subscription, including using your location data to determine your country pricing.</p>
        
        <h1 className={h1Style}>How Information is Shared</h1>
        <p className={textStyle}>We do not sell your personal information for monetary value. We may share personal information in accordance with your preferences, as needed to run our business and provide the Services, and where required for legal purposes, as set forth below. In addition, we may sell or share aggregated data about our users, as described in more detail in the “Aggregate Information” section below.</p>
        <h2 className={h2Style}>Service Providers</h2>
        <p className={textStyle}>We may share your information with third parties who provide services to Argos LLC such as supporting, improving, promoting and securing the Services, processing payments, or fulfilling orders. These service providers only have access to the information necessary to perform these limited functions on our behalf and are required to protect and secure your information. We may also engage service providers to collect information about your use of the Services over time on our behalf, to promote Argos LLC or display information that may be relevant to your interests on the Services or other websites or services.</p>

        <h2 className={h2Style}>Publicly Available Information</h2>
        <p className={textStyle}>When you join the Argos LLC community as an individual of 18 years of age or older, your profile and your activities are set to be viewable by everyone by default. Your name and other profile information is viewable by other Argos LLC users and the public and, subject to your privacy controls, additional information and content you share may also be viewable. For example, your media content and routes may be accessed by other Argos LLC users and non-users or viewable on publicly accessible Argos LLC pages or in search engine results.</p>
        <p className={textStyle}>When you join the Argos LLC community as an individual under the age of 18, your profile and your activities are set to be viewable by followers only by default. In order for another Argos LLC user to be able to see your detailed profile information or your activities, the Argos LLC user must first request to follow you and you must accept that request. For example, a Argos LLC user will not be able to see your uploaded activities or photos until after you have granted the Argos LLC user permission to follow you.</p>
        <p className={textStyle}>We provide a variety of privacy controls to manage the sharing of your information and encourage our users to adjust their controls to align with their desired experience.</p>

        <h2 className={h2Style}>Sharing Information and Activities</h2>
        <p className={textStyle}>We share your information with other Argos LLC users and the public in accordance with your privacy controls. You can change the visibility of the activities you upload to Argos LLC . Also, you can tell us about important locations, such as your home or work address, by using our "Hide a Specific Address" feature in your privacy controls. We will hide any portion of your activity on your activity map that starts or ends near your hidden addresses. Using Argos LLC Beacon, you can choose to invite your trusted contact(s) to view your live location while recording activities. You can also share your activities with your contacts via text, email, or on social media applications like Meta, Instagram, and Twitter. If you link your Argos LLC account to other social networks and share your activities, they will be viewable on such third-party platforms, including your location information. You should use caution when sharing information via third parties and you should carefully review the privacy practices of such third parties.</p>

        <h2 className={h2Style}>Targeted Advertising</h2>
        <p className={textStyle}>We may use the information we collect and receive about you to provide you with targeted advertising if you accept non-essential cookies using our cookie banner. You may opt-out of targeted advertising by clicking the “Do Not Share My Personal Information” link in the footer below or in our app by clicking on the “Personal Information Sharing” link in your Privacy Controls and following the instructions.</p>

        <h2 className={h2Style}>Third Party Business via API or Other Integrations</h2>
        <p className={textStyle}>We enable you to share your information and content with third party apps, plugins, or websites that integrate with the Services, as well as with third parties who work with Argos LLC to offer an integrated feature, such as a challenge sponsor, media streaming, or tracking device. You can choose to share your profile data and activity data (including private activities) with these third parties. Information collected by these third parties is subject to their terms and policies and may not provide you with the same privacy controls that are available on Argos LLC (for example, hiding a specific address or the start and end points on activity maps). Argos LLC is not responsible for the terms or policies of third parties.</p>

        <h2 className={h2Style}>Aggregate Information</h2>
        <p className={textStyle}>Argos LLC may deidentify and aggregate the information you and others make available in connection with the Services and post it publicly or share it with third parties. Examples include information about equipment, usage, demographics, routes, performance, and challenge participation and completion. Argos LLC may use, sell, license, and share this aggregated information with third parties for research, business or other purposes such as to improve walking, running or riding in cities via Argos LLC Metro or to help our partners understand more about users, including the people who use their products and services. Argos LLC also uses aggregated data to generate our Global Heatmap and other community-powered features such as Points of Interest and Start Points. Please visit your privacy controls if you would like to opt out of Argos LLC using your information for these purposes.</p>
        
        <h2 className={h2Style}>Subsidiaries and Acquirors of our Business or Assets</h2>
        <p className={textStyle}>We may share your information with our subsidiaries, who are required to handle your personal information in accordance with their own Privacy Policies.</p>
        <p className={textStyle}>If Argos LLC becomes involved in a business combination, securities offering, bankruptcy, reorganization, dissolution or other similar transaction, we may share or transfer your information in connection with such transaction.</p>

        <h2 className={h2Style}>Legal Requirements</h2>
        <p className={textStyle}>We may preserve and share your information with third parties, including law enforcement, public or governmental agencies, or private litigants, within or outside your country of residence, if we determine that such disclosure is allowed by the law or reasonably necessary to comply with the law, including to respond to court orders, warrants, subpoenas, or other legal or regulatory process. We may also retain, preserve or disclose your information if we determine that this is reasonably necessary or appropriate to: (1) prevent any person from death or serious bodily injury; (2) to address issues of national security or other issues of public importance; (3) to prevent or detect violations of our Terms of Service or fraud or abuse of Argos LLC or its users (4) or to protect our operations or our property or other legal rights, including by disclosure to our legal counsel and other consultants and third parties in connection with actual or potential litigation.</p>

        <h1 className={h1Style}>Managing Your Settings</h1>
        <h2 className={h2Style}>Privacy Controls</h2>
        <p className={textStyle}>Argos LLC offers several features and settings to help you manage your privacy and share your activities. Most privacy controls are located in your privacy controls page, but some are specific features.</p>
        <h2 className={h2Style}>Adjust Notification and Email Preferences</h2>
        <p className={textStyle}>Argos LLC offers various ways to manage the notifications you receive. You can choose to stop receiving certain email notifications by indicating your preferences here. You may also unsubscribe from these emails by following the instructions contained at the bottom of these messages. In our app, you can access your “Push Notifications” in the settings menu. Where permitted by local regulations, we may opt you into marketing-related communications if you substantially interact with the Services or purchase a subscription. We may also send you periodic communications asking if you would like to opt into receiving marketing-related communications.</p>
        <p className={textStyle}>If you receive marketing communications from one or more of our subsidiaries, you must opt-out individually from each subsidiary you are receiving brand-specific marketing from.        </p>
        <p className={textStyle}>Any administrative or service-related emails (for example, to confirm a purchase, to notify you of pricing changes, to deliver a training plan you requested, or provide an significant update to our policies, etc.) may not offer an option to unsubscribe as they are necessary to provide the Services you requested. You are responsible for providing us with a valid email address and keeping it updated to ensure you get these email notifications.</p>
        <h2 className={h2Style}>Updating Account Information</h2>
        <p className={textStyle}>You may correct, amend or update profile or account information at any time by adjusting that information in your account settings. If you need further assistance correcting inaccurate information, please contact Argos LLC at Argosapp.net</p>

        <h1 className={h1Style}>Deleting Information and Accounts and Downloading Your Data</h1>
        <p className={textStyle}>You can delete your account or download your data using our self-service tools.        </p>
        <p className={textStyle}>After you make an account deletion request, we permanently and irreversibly delete your personal information from our systems, including backups. Once deleted, your data, including your account, activities and place on leaderboards cannot be reinstated. Following your deletion of your account, it may take up to 45 days to delete your personal information and system logs from our systems. Additionally, we may retain information where deletion requests are made to comply with the law and take other actions permitted by law.</p>
        <p className={textStyle}>Note that we do not have control over content you have shared directly with others, such as photos or videos on other social media platforms, or that others may have copied. In other words, content or information may remain available after you have deleted your account or deleted specific information from your own profile. Your public profile may be displayed in search engine results until the search engine refreshes its cache.</p>
        <p className={textStyle}>Argos LLC also provides you the option to remove individual activities you have posted without deleting your account. Once removed, the activities may remain on Argos LLC 's systems until you delete your account.</p>
        <h2 className={h2Style}>Children's Privacy</h2>
        <p className={textStyle}>Our services are not intended for, nor directed to, children under 13 years of age. We use technical measures to prevent children under 13 years of age from creating an account and therefore do not knowingly collect personal information from anybody under 13 years of age. If you are under 13 years of age, do not use the Services</p>
        <p className={textStyle}>Moreover, we strive to provide additional privacy and safety protections for individuals under 18 years of age. For example, when users under 18 years of age create an account, their profile and activities are set by default to be viewable by followers only. We also may limit how we collect or process the personal information of individuals under 18 years of age. For example, you must be at least 16 years of age to upload heart rate data or receive heart rate analysis.</p>
        <h2 className={h2Style}>How We Protect Information</h2>
        <p className={textStyle}>Argos LLC implements technical, physical, and organizational measures and controls to safeguard and protect the transmission and storage of the data we collect. We employ reasonable protections for your information that are appropriate to its sensitivity.</p>
        <p className={textStyle}>Please be aware that despite our efforts, we cannot guarantee absolute security of your account or information. In addition, you can take steps to protect your account and information such as creating a unique password for Argos LLC that is not easily guessed and that you don't use anywhere else, not sharing your password with others, and promptly reporting suspicious activity or unauthorized account access.</p>
        <h2 className={h2Style}>Your Rights and Our Legal Bases</h2>
        <p className={textStyle}>We provide the same suite of privacy controls to all of our users worldwide. Particular rights may be available to you if you reside in certain locations, such as the EEA, Brazil or certain U.S. states such as California. Learn more about your rights and how to exercise them.</p>
        <h2 className={h2Style}>Your Legal Rights in the EEA</h2>
        <p className={textStyle}>If you reside in the EEA, you have the right to access, rectify, download or erase your information, as well as the right to restrict and object to certain processing of your information. Argos LLC 's lead supervisory authority in the EEA is the Data Protection Commission of Ireland.</p>

        <h2 className={h2Style}>Our Legal Bases</h2>
        <p className={textStyle}>Argos LLC relies on a number of legal bases to collect, use, share, and otherwise process the information we have about you for the purposes described in this Privacy Policy, including:</p>
        <ul className={textStyle}>
            <li>&#8226; as necessary to provide the Services and fulfill our obligations pursuant to the Terms of Service. For example, we cannot provide the Services unless we collect and use your location information;            </li>
            <li>&#8226; where you have consented to the processing;</li>
            <li>&#8226; where necessary to comply with a legal obligation, a court order, or to exercise and defend legal claims;</li>
            <li>&#8226; to protect your vital interests, or those of others, such as in the case of emergencies; and
            </li>
            <li>&#8226; where necessary for the purposes of Argos LLC 's or a third party's legitimate interests, such as our interests in protecting our users, our partners' interests in collaborating with our users, and our commercial interests in ensuring the sustainability of the Services.</li>
        </ul>
        <h2 className={h2Style}>Cross Border Data Transfers</h2>
        <p className={textStyle}>The Services are operated from the United States. If you are located outside of the United States and choose to use the Services or provide information to us, you acknowledge and understand that your information will be transferred, processed and stored in the United States, as it is necessary to provide the Services and perform the Terms of Service.</p>
        <p className={textStyle}>Whenever we transfer personal data internationally, we use legal mechanisms, such as Standard Contractual Clauses, to ensure data transfers comply with applicable law.

</p>
        <h2 className={h2Style}>Retention of Information</h2>
        <p className={textStyle}>We retain information as long as it is necessary to provide the Services to you and others, subject to any legal obligations to further retain such information. Information associated with your account will generally be kept until it is no longer necessary to provide the Services or until your account is deleted or becomes inactive. In making these determinations, we consider the amount, nature, and sensitivity of the personal information, the purposes for which the information is processed, whether we can achieve those purposes through other means, and applicable legal requirements.</p>
        <p className={textStyle}>In addition, you can delete some items of information (e.g., profile information) and you can remove individual activities from view on the Services without deleting your account. For example, if you withdraw your consent to Argos LLC processing your health-related information, Argos LLC will thereafter delete all health-related information from activities you upload. Following your deletion of your account, it may take up to 45 days to fully delete your personal information and system logs from our systems. Additionally, we may retain information to comply with the law, prevent fraud, collect fees, resolve disputes, troubleshoot problems, assist with investigations, enforce the Terms of Service and take other actions permitted by law. The information we retain will be handled in accordance with this Privacy Policy.</p>
        <p className={textStyle}>Information connected to you that is no longer necessary and relevant to provide our Services to you may be de-identified or aggregated with other non-personal data to provide insights that are commercially valuable to Argos LLC , such as statistics of the use of the Services. For example, we may retain publicly available segments or routes and other depersonalized geolocation information to continue to improve the Services, and we use aggregated information in Argos LLC Metro and our Global Heatmap. This information will be de-associated from your name and other identifiers.</p>
        <h2 className={h2Style}>Privacy Policy Updates</h2>
        <p className={textStyle}>Argos LLC reserves the right to modify this Privacy Policy at any time. Please review it occasionally. If Argos LLC makes changes to this Privacy Policy, the updated Privacy Policy will be posted in a timely manner. If we make changes we deem to be material, we will provide a prominent notice. If you object to any changes to this Privacy Policy, you should stop using the Services and delete your account.</p>

    </div>
    );
}