export default function Text() {
    const h1Style = "scroll-m-20 text-2xl font-bold tracking-tight lg:text-2xl py-2";
    const h2Style = "scroll-m-20 text-xl tracking-tight lg:text-xl py-2";
    const textStyle = "py-2 text-xs";
  return (
    <div>
        <h1 className={h1Style}> 
            Gradient LLC Terms of Service
        </h1>
        <h2 className={h2Style}>
        Last Update: 10/05/2023 (Subscription/Pay Wall Version not implemented in Version 1.0)
        </h2>
        <p className={textStyle}>
        The Gradient LLC websites, related mobile applications, and services (collectively, the “Services”) are made available to you by Gradient LLC, subject to these Terms of Service (the “Terms”) and in accordance with the Gradient LLC Privacy Policy (the “Privacy Policy”). More information about the Services may be found at gradientapp.net. You agree to comply with these Terms and any supplemental terms which Gradient LLC makes available to you on the Services, which shall form a part of the Terms. Gradient LLC reserves the right to review accounts and user actions on the Services to ensure compliance with our Terms.
        </p>
        <p className={textStyle}>
        BY ACCESSING, USING, UPLOADING, OR DOWNLOADING ANY INFORMATION OR MATERIALS TO OR FROM THE SERVICES, OR BY INDICATING YOUR ASSENT TO THESE TERMS BY CREATING AN ACCOUNT, CLICKING “SIGN UP,” OR ANY SIMILAR MECHANISM, YOU ARE AGREEING TO THESE TERMS. IF YOU DO NOT AGREE TO THESE TERMS, DO NOT ACCESS OR USE THE SERVICES. This agreement was written in English. To the extent a translated version of the Terms conflict with the English version, the English version controls.
        </p>
        <p className={textStyle}>
        If you access or use the Services on behalf of a company or other entity, you represent that you have the authority to bind such entity and its affiliates to these Terms and that it is fully binding on them. In such a case, the term “you” will refer to such an entity and its affiliates. If you do not have authority, you may not access or use the Services. These Terms contain disclaimers of warranties and limitations on liability that may be applicable to you.
        </p>
        <p className={textStyle}>
        The Gradient LLC Services cannot be provided, and the agreement described in these Terms of Service cannot be performed without Gradient LLC processing data about you and other Gradient LLC users, including your location data. Processing of the data you share with Gradient LLC, including location data, is essential to the Services we provide and is a necessary part of our performance of the agreement we have with you.
        </p>
        <p className={textStyle}>
        Notice Regarding Dispute Resolution: These Terms contain provisions that govern how disputes between you and Gradient LLC are resolved, including an agreement to arbitrate, which will, unless you reside in the European Union, with limited exception, require you to submit claims you have against us to binding and final arbitration and limit you to claims against Gradient LLC on an individual basis, unless you opt-out in accordance with the instructions below.
        </p>

        <h1 className={h1Style}> 
        Highlights:
        </h1>
        <ul className={textStyle}>
            <li>&#8226; Your privacy is extremely important to us. Learn about how we collect and utilize your personal information in our Privacy Policy.</li>
            <li>&#8226; You have the freedom to cancel your subscription or remove your account at any time.</li>
            <li>&#8226; While you own your content, you grant us the right to utilize it.</li>
            <li>&#8226; We anticipate respectful behavior, and we have the right to disable your account or content access if you violate our rules.</li>
            <li>&#8226; Gradient LLC is not held liable for your activities, and no warranties are provided by Gradient LLC.</li>
            <li>&#8226; If you breach our Terms, we can suspend or terminate your account.</li>
            <li>&#8226; We welcome your feedback and request your permission to use it.</li>
            <li>&#8226; You consent to arbitration in case of disputes between us (unless you are an EU resident).</li>
            <li>&#8226; We offer straightforward ways to get in touch if you have inquiries or require assistance.</li>     
        </ul>

        <h1 className={h1Style}>Gradient LLC Registration and Accounts</h1>
        <p className={textStyle}>The Services are intended solely for individuals who are 13 years old or the higher age required in your country to use the Services. If you are below the legal age to enter a binding contract in your jurisdiction, you confirm that your parent or legal guardian has reviewed and consented to these Terms on your behalf.</p>
        <p className={textStyle}>To utilize the Services, registration is necessary. By doing so, you agree to: (a) provide accurate, current, complete, and truthful information about yourself ("User Data") and (b) keep the User Data up to date. You acknowledge that Gradient LLC may utilize your User Data to furnish the Services you access or use, and as further detailed in these Terms and our Privacy Policy. Additionally, you undertake to establish just one account solely for your personal use and not share your account or Gradient LLC subscription with others. Should you supply any User Data that is incorrect, outdated, or create multiple accounts, if Gradient LLC has reasonable grounds to suspect inaccuracies in such user Data, Gradient LLC holds the right to suspend or terminate your account and reject present or future usage of the Services. In consideration for using the Services, you assert that you are not prohibited by any applicable jurisdiction's laws from receiving services.</p>
        <p className={textStyle}>The security of the password linked to your account and controlling access to your password, your computing devices, and mobile devices while logged into the Services are solely your responsibility. You assume accountability for all actions originating from your account or from your computing and mobile devices. We make efforts to employ reasonable security measures to prevent unauthorized entry to your account. However, we are unable to guarantee complete security of your account, your Content (as defined below), or the personal information you provide. We are unable to ensure that our security measures will thwart illegal third parties from gaining unauthorized access to the Services or its contents. You undertake to immediately notify Gradient LLC of any unauthorized use of your account or password, or any other security breach. Furthermore, you acknowledge understanding the risks linked to unauthorized access to User Data or any other information or content submitted to Gradient LLC. The use of intricate and unique passwords is strongly recommended for security purposes.</p>
        <p className={textStyle}>Registration for or logging into your account through a third-party network, such as Facebook or Google, is possible. If you choose to do so, you hereby grant Gradient LLC permission to pre-fill your account's registration and other pertinent information fields and/or use these third-party credentials to log you into your account. When you associate your account with a third-party network, you agree to adhere to the terms, conditions, and policies of such a third party.</p>
        <p className={textStyle}>Through specific Services linking to the Google Maps API, you are bound by the Google Maps/Google Earth Additional Terms of Service (inclusive of the Google Privacy Policy) in connection with your utilization of such Services.</p>

        <h1 className={h1Style}>Payments and Fees</h1>
        <h2 className={h2Style}>Gradient LLC Payments</h2>
        <p className={textStyle}>To make any payment, you must specify and furnish details about your chosen payment method (e.g., credit card, online payment service, a third-party platform like iTunes or Google Play, or any other payment method facilitated by Gradient LLC) (the “Payment Method”). Upon providing your payment information, you grant us and specific third-party service providers, payment card networks, and payment processors permission to receive, store, and encrypt your payment details. You can change to a different Payment Method or update your information by visiting [Website URL]/account. For those who made payments via the Google Play or iTunes store, altering the Payment Method can be done through the corresponding store account. Strava does not offer refunds or credits, except as outlined in these Terms. If your payment provider identifies fraudulent charges on your account due to the use of your Payment Method for the Services, please contact us immediately via [Support URL].</p>
        <h2 className={h2Style}>Fees</h2>
        <p className={textStyle}>Certain functionalities of the Services may require payment of subscription fees. Subscription fees, including any applicable taxes, can be paid either monthly or annually. All subscription fees are due in advance. If users switch from monthly to annual subscriptions, the annual rates will come into effect starting from the upcoming billing date. By utilizing the Services, you agree to pay the subscription fees and any other charges related to your Gradient LLC account, whether on a one-time or subscription basis. Gradient LLC reserves the right to adjust subscription fees, associated taxes, or introduce new fees with reasonable advance notice.</p>
        <h2 className={h2Style}>Auto-Renewal</h2>
        <p className={textStyle}>Subscription fees will be automatically charged at the commencement of the applicable monthly or annual period. These fees will continue to auto-renew until your subscription is downgraded or terminated. Your subscription fee will match the initial charges, unless you receive prior notice of a change. You retain the option to cancel your subscription at any time, as explained below.</p>
        <h2 className={h2Style}>Cooling Off</h2>
        <p className={textStyle}>For residents outside the United States, you might have the right to reconsider and receive a complete refund within fourteen (14) days (the “Cooling-off Period”), on the condition that you have not logged in, redeemed, or commenced using the Services as a subscriber during the Cooling-off Period.</p>

        <h1 className={h1Style}>Gradient LLC Content and Conduct</h1>
        <h2 className={h2Style}>Ownership of and Use of Content</h2>
        <p className={textStyle}>You possess ownership of the data, information, text, software, sound, images, photographs, graphics, videos, messages, posts, tags, or other materials you make accessible in connection with the Services (“Content”), whether distributed publicly, transmitted privately, or submitted via a third-party API (e.g., a video submitted through Zwift). Public segments and routes produced using the Services are not categorized as Content. You extend to us a non-exclusive, transferable, sub-licensable, royalty-free, global license to utilize, reproduce, modify, adapt, publish, translate, generate derivative works from, distribute, publicly perform, and display any Content and any name, username, or likeness you post on or in relation to the Services across all present and future media formats and channels without requiring compensation from you. This license concludes when you erase your Content or deactivate your account.</p>
        <p className={textStyle}>You recognize that you, and not Gradient LLC, hold full responsibility for all Content you upload, post, transmit via email, transmit, or otherwise make available through the Services. Gradient LLC does not consistently monitor or review the Content shared on the Services by other users and, as a result, does not guarantee the precision, integrity, or quality of such Content. Gradient LLC may, at its sole discretion, assess, monitor, hide, reject, or delete any Content, or eliminate Content that violates the Terms or is otherwise objectionable. You understand that, due to your use of the Services, you may be exposed to Content that is offensive, indecent, or objectionable. In no circumstances will Gradient LLC be liable in any manner for any Content, including, but not limited to, any errors or omissions in any Content or any loss or damage incurred due to the utilization of any Content provided on the Services. You undertake all risks linked to the use of any Content obtainable through the Services, including reliance on the accuracy, completeness, or usefulness of such Content.</p>
        <p className={textStyle}>You accept that Gradient LLC is not liable for and does not endorse Content posted on the Services. If your Content breaches these Terms, you may be legally accountable for that Content. Between you and Gradient LLC, any Content shall be deemed non-confidential and non-proprietary, and we shall not be accountable for any utilization or exposure of the Content. You acknowledge and consent to the fact that your association with Gradient LLC is not of a confidential, fiduciary, or distinct nature, and that your choice to provide any Content does not place Gradient LLC in a distinct position from that of the general public, including in relation to your Content. Your Content will not be subject to any confidentiality obligation on the part of Gradient LLC, except as outlined in our Privacy Policy and your privacy controls, and Gradient LLC shall not be responsible for any usage or disclosure of the Content you provide.</p>
        <p className={textStyle}>The Services might allow you to categorize particular Content you submit to the Services as private, public, or solely accessible to specific Services users. Gradient LLC will uphold the confidentiality of such Content according to your selections. However, if you do not choose to designate your Content as private or exclusively available to a limited group of users or if you subsequently modify such categorization to permit such Content's accessibility to everyone, you are accountable for the public nature of the content. Kindly refer to our Privacy Policy for detailed guidance on managing your privacy settings.</p>
        <p className={textStyle}>You grant us permission to utilize your profile name, profile image, and details about your activities and actions you've taken, including your use of third-party products, services, or devices, in advertisements, offers, and other commercial contexts on the Gradient LLC service without entitlement to compensation. For instance, we may display to your Gradient LLC followers that you utilize a specific device, product, or service provided by a brand that has compensated us to showcase its advertisements on Gradient LLC. You can adjust settings to prevent your profile name and profile image from appearing in an advertisement.</p>
        <p className={textStyle}>The Services are designed for your individual and non-commercial usage. You may not alter, duplicate, distribute, transmit, display, perform, reproduce, publish, license, produce derivative works from, transfer, or sell any portion of the Services, access to the Services, or usage of Content, for commercial purposes. You are granted a restricted, non-exclusive authorization to generate a text hyperlink to the Services, only for non-commercial purposes. This link should not misrepresent Gradient LLC or its products or services, and the linked site should not include any offensive, illegal, pornographic, harassing, or objectionable material. Moreover, you are granted permission to employ any RSS feeds featured on the Services for your individual, non-commercial usage, adhering strictly to the guidelines provided on the Services. We retain the authority to rescind these licenses universally or your entitlement to use particular links or RSS feeds, at any time and with or without reason.</p>
        <p className={textStyle}>You comprehend that the use of particular features within the Services might necessitate the procurement of third-party equipment or materials (e.g., GPS systems). While Gradient LLC may suggest equipment or materials from particular third-party suppliers, Gradient LLC bears no responsibility for your acquisition or utilization of any third-party equipment or materials. Gradient LLC does not ensure that third-party equipment or materials will function compatible with the Services or remain free from errors.</p>
        <p className={textStyle}>You acknowledge that you are liable for any charges associated with transmitting communications via your device. You hereby recognize your right to communicate with your contacts via the Services.        </p>
        <p className={textStyle}>You assert and guarantee that: (i) you are authorized to establish your account, either individually or on behalf of an entity; (ii) you own the Content you post on or through the Services or possess the right to grant the rights and licenses as defined in these Terms; (iii) the posting and utilization of your Content on or through the Services do not and will not infringe upon, misappropriate, or violate the rights of any third party, which includes privacy and data protection rights, publicity rights, copyrights, trademarks, or other intellectual property rights; and (iv) you will cover all royalties, fees, and any other payments due by virtue of the Content you post on or through the Services.
        Gradient LLC: Content and Conduct Restrictions</p>
        <p className={textStyle}>Gradient LLC’s Acceptable Use Policies describe restrictions on content and conduct and are incorporated by reference into these terms. You agree to comply with those policies.</p>

        <h2 className={h2Style}>Interactions with Users</h2>
        <p className={textStyle}>The Services function as a venue to connect users in a virtual information place. As a neutral facilitator, Gradient LLC is not directly involved in the actual interactions between users using the Services. As a result, Gradient LLC has no control over the truth, accuracy, quality, legality, or safety of postings made by users using the Services. Gradient LLC shall have no responsibility to confirm the identity of users. Gradient LLC shall also have no responsibility to confirm or verify the qualifications, background, or abilities of users using the Services. You shall at all times exercise common sense and good judgment when dealing with any users using the Services.</p>
        <p className={textStyle}>If you elect to use our features to inform your contacts about the Services, track your activities via Gradient LLC Beacon, or share your information with others, Gradient LLC may require you to provide contact information. Gradient LLC may contact that friend via a one-time email or text message. You represent that you are authorized to provide any third-party contact information that you provide to Gradient LLC, that you are authorized to use such information to contact (including for Gradient LLC to contact on your behalf) the third party, and that Gradient LLC may process it pursuant to the Privacy Policy.</p>

        <h2 className={h2Style}>Professional and Verified Users</h2>
        <p className={textStyle}>If you are a professional user, Gradient LLC ma    y choose to verify your Gradient LLC account and place a badge on your profile indicating your professional status. Verified professional users on Gradient LLC will receive a free subscription. We expect all users to honor the Gradient LLC Community Standards and code of conduct as listed in these Terms of Service. We reserve the right to remove your verified status and badge, as well as cease your free subscription, at any time.</p>

        <h2 className={h2Style}>Home Gym Community Groups</h2>
        <p className={textStyle}>Gradient LLC creates and administers certain Home Gym Community Groups as well as the Home Gym Community Groups verification program. Gradient LLC may choose to verify certain Home Gym Community Groups and place a badge on their profile page. We reserve the right to revoke or transfer ownership of Home Gym Community Groups, remove content, remove a Home Gym Community Groups’s verified status and badge, and remove a Home Gym Community Groups at any time. If you request a transfer of ownership of a Home Gym Community Groups, Gradient LLC may require you to provide certain documentation.</p>
        <p className={textStyle}>If you, as an user or partner, create a Home Gym Community Groups on Gradient LLC, you are responsible for ensuring that your Home Gym Community Groups: (a) abides by these Terms of Service and our Community Standards; (b) does not claim, suggest an affiliation with, or impersonate Gradient LLC, whether by using Gradient LLC’s intellectual property or otherwise; (c) has the right to use or post all Home Gym Community Groups content, third party or otherwise, including rights to use name(s), logo(s), images, trademarks, trade dress, service marks, copyrights, or other intellectual property; and (d) does not, in Gradient LLC’s sole discretion, use the Home Gym Community Groups to inappropriately advertise or promote any contests, sweepstakes, or other promotions. Home Gym Community Groups administrators hereby agree to indemnify and hold Gradient LLC harmless from any and all claims arising out of your Home Gym Community Groups, including but not limited to claims of intellectual property infringement.</p>

        <h2 className={h2Style}>Third Parties</h2>
        <p className={textStyle}>Third party products and services made available on the Services are made and offered directly by the applicable third party. When you pursue or purchase any such product or service, you acknowledge that you are contracting directly with such a third party and not with Gradient LLC. Your interaction with, or participation in promotions of, third parties found on or through the Services, including payment and delivery of goods or services, and any other terms, are solely between you and such third party. You are not obligated to use or transact business with any third party that appears on the Services. YOU AGREE THAT GRADIENT LLC SHALL NOT BE LIABLE FOR ANY LOSS OR DAMAGES OF ANY KIND INCURRED BY YOU AS THE RESULT OF ANY OF YOUR DEALINGS WITH THIRD PARTY SERVICE PROVIDERS OR ADVERTISERS AVAILABLE THROUGH THE SERVICES.</p>
        <p className={textStyle}>Gradient LLC or third parties may provide links to other internet sites or resources through the Services. Gradient LLC does not endorse and is not responsible or liable for any content, information, advertising, products, or other materials on or available from such sites or resources. You acknowledge and agree that Gradient LLC is not responsible for the availability of such external sites or resources.</p>

        <h2 className={h2Style}>Electronic Communications</h2>
        <p className={textStyle}>The Services may provide you with the ability to send or post messages to forums or chat rooms, speak via internet voice connections, or send similar messages and communications to third party service providers, advertisers, your personal contacts, other users, and/or Gradient LLC. You agree to use communication methods available on the Services only to send communications and materials related to the subject matter for which Gradient LLC provided the communication method, and you further agree that all such communications by you shall be deemed your Content and shall be subject to and governed by the Terms and applicable law (including laws regulating direct marketing communications with which you will need to comply with, as applicable). By using communication methods available on the Services, you agree that</p>
        <p className={textStyle}>(a) all communications methods constitute public, and not private, means of communication between you and the other party or parties, (b) communications sent to or received from third party service providers, advertisers, or other third parties are not endorsed, sponsored, or approved by Gradient LLC (unless expressly stated otherwise by Gradient LLC), and (c) communications are not routinely pre-reviewed, post-reviewed, screened, archived, or otherwise monitored by Gradient LLC in any manner, though Gradient LLC reserves the right to do so at any time at its sole discretion. You agree that all notices, disclosures, and other communications that we provide to you electronically shall satisfy any legal requirement that such communications be in writing.</p>

        <h2 className={h2Style}>Proprietary Rights</h2>
        <p className={textStyle}>You acknowledge and agree that the Services, any necessary software used in connection with the Services (if any), any aggregated data based on Content on the Services, and any Content available or made available on the Services contain proprietary and confidential information that is protected by applicable intellectual property and other laws. Except as expressly permitted by applicable law or authorized by Gradient LLC or applicable third party service providers or advertisers, you agree not to modify, rent, lease, loan, sell, distribute, or create derivative works based on the Services, the software, or Content available on the Services (other than Content that you may submit), in whole or in part.</p>
        <p className={textStyle}>Gradient LLC grants you a personal, revocable, non-transferable, non-sublicensable, and non-exclusive right and license to access and use the Services; provided that you do not (and do not allow any third party to) copy, modify, create a derivative work from, reverse engineer, reverse assemble, or otherwise attempt to discover any source code, sell, assign, sublicense, grant a security interest in, or otherwise transfer any right in the Services, except where permitted by law. You agree not to access the Services by any means other than through the interfaces that are provided by Gradient LLC.</p>
        <p className={textStyle}>The term GRADIENT LLC, the Gradient LLC logo, and other Gradient LLC logos and product and service names are the exclusive trademarks of, and are owned by, Gradient LLC, and you may not use or display such trademarks in any manner without Gradient LLC’s prior written permission. Any third-party trademarks or service marks displayed on the Services are the property of their respective owners.</p>
        <p className={textStyle}>Gradient LLC reserves all rights in the Services not expressly granted to you here.</p>
    </div>
  );
}